### ISSUE TITLE
Autocomplete not cleared out when new field selected

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3301] opened 2022-09-23 11:17 UTC
### Description

Each time a new field is selected, the autocomplete values for that field is added to any existing values in the dropdown.

The solution is probably to clear out autocomplete values every time the field is changed.

### To Reproduce
1. Select field
2. Trigger autocomplete
3. Select a different field
4. Trigger autocomplete (these new values will be added to values returned in step 2)

### App Version

v0.263.0

**Comment by TuringLovesDeathMetal** [comment] 2022-09-23 13:49
hmmm, I can't reproduce this 🤔 here's what I tried: 
https://www.loom.com/share/b084d830414e411f897e56170eb06aa3

Maybe I'm misunderstanding what you mean by `trigger autocomplete`?

**Comment by gordonkjlee** [comment] 2022-09-23 14:05
Sorry, totally forgot about the demo environment!
https://user-images.githubusercontent.com/7281432/191978967-f32b31c4-b294-423a-8f14-e023035416a1.mp4

**Comment by ZeRego** [comment] 2022-09-23 14:11
Should be fixed in https://github.com/lightdash/lightdash/pull/3296

**Closed** 2022-09-23 14:40 UTC
Labels: 🐛 bug
