### ISSUE TITLE
Custom metrics can be longer than allowed sql identifier length

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9565] opened 2024-03-27 22:37 UTC
### Description

Standard SQL (postgres / redshift) limits identifiers to 127 bytes, but we've seen longer identifiers generated for Lightdash metrics.

Two issues here:

- The failing behaviour is confusing, when you request a 140 char field in Lightdash, postgres/redshift will respond with a truncated 127 char column name. Lightdash doesn't match these up but also doesn't throw an error. So the query executes without error but shows a column in the UI with no values populated. We should have an explicit error here if the schema in the query results don't match the requested fields
- We need to generate shorter identifiers for custom metrics, can they be anonymous? Or are we relying on a specific format?

**Comment by owlas** [comment] 2024-03-27 22:38
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C05UPNC0LGP/p1711484380885419?thread_ts=1711484380.885419&cid=C05UPNC0LGP

**Comment by TuringLovesDeathMetal** [comment] 2024-03-28 09:10
closing as a duplicate of https://github.com/lightdash/lightdash/issues/7759

**Closed by TuringLovesDeathMetal** 2024-03-28 09:10 UTC
Labels: 🐛 bug
