### ISSUE TITLE
I can't save a chart from the SQL runner if there is only one column included

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12007] opened 2024-10-18 18:38 UTC
### Description

Charts from the SQL runner are not able to be saved when there's only one column of data

### Steps to Reproduce the Bug or Issue

https://www.loom.com/share/df1c64d645ce4553af339e6d33c36fbe

### Cloud or self-hosting

None

**Comment by magnew** [comment] 2024-12-27 16:51
Closing as a duplicate of #13013

**Closed by magnew** 2024-12-27 16:51 UTC
Labels: 🐛 bug, 🏃‍♀️ SQL runner
