### ISSUE TITLE
I wish I could use user roles to determine which spaces users can see

### ISSUE THREAD

**Issue by pinkbaka** [lightdash/lightdash#7570] opened 2023-10-20 16:58 UTC
### Description

Create a way to limit what users can see based on their job role by using user attributes. Not every organizational viewer needs to or should see every space.

### What problem does this solve?
It's a pain to invite everyone to every space I want them to see. Not every user needs to see every page and this can just distract them. For example, I want to separate spaces for IC's vs. Managers.

**Comment by TuringLovesDeathMetal** [comment] 2024-04-02 07:53
Closing this as a duplicate of #7477 (which has been completed)

**Closed by TuringLovesDeathMetal** 2024-04-02 07:53 UTC
Labels: ✨ feature-request
