### ISSUE TITLE
data discrepancy when plotting yearly data points using non-UTC time zone

### ISSUE THREAD

**Issue by Shifan-Gu** [lightdash/lightdash#8215] opened 2023-12-05 17:18 UTC
### Description

when plotting yearly data points using the PST timezone, the default date time value used to format tooltip is resolved to the first date of the year in UTC, but when formatting the tooltip content, it uses the literal value of data point but resolved to a date object using local timezone, which leads to the discrepancy.

e.g. In the given example below, data point value is "2020-01-01", but tooltip value is resolved to "2019-12-31" (i guess) which eventually showing "2019" as result, because the timezone is set to PST, which is (-0800) hours of UTC time.

### To Reproduce

https://github.com/lightdash/lightdash/assets/101873365/90f58dfd-427b-4f44-9636-f095f3e8d68d

### App Version
0.893.0

**Comment by TuringLovesDeathMetal** [comment] 2023-12-06 09:47
👋 Hey Shifan. 

I'm going to close this issue because I think it's a duplicate of this one here: https://github.com/lightdash/lightdash/issues/7527

We're just about to close a PR on #7527, so hopefull it should be fixed soon 🤞

**Closed by TuringLovesDeathMetal** 2023-12-06 09:47 UTC
Labels: 🐛 bug

**Comment by Shifan-Gu** [comment] 2024-01-12 13:45
Hi @TuringLovesDeathMetal 

This issue still exists in the latest version `v0.936.3`, could you re-open it?

https://github.com/lightdash/lightdash/assets/101873365/278a2f03-4d7f-4840-a1af-4b5213f18e27
