### ISSUE TITLE
Chart hover info for time ranges doesnt match results table

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6610] opened 2023-08-03 16:08 UTC
### Description

The hover elements in time-based charts don't match whats in the results table or the axes. It looks like we are showing the bucket start in the hover elements and the 'bucket name' in the results. 

<img width="1169" alt="Screenshot 2023-08-03 at 17 54 05" src="https://github.com/lightdash/lightdash/assets/1864179/403e5854-3382-48b9-b0e7-cd5e6de20e65">

### To Reproduce

Create a chart with a Date-month dimension on the x-axis. Hover over the elements and notice the timestamp is very weird. 

### App Version

Version: v0.717

**Comment by TuringLovesDeathMetal** [comment] 2023-09-21 10:38
Clsoing this as a duplicate of: https://github.com/lightdash/lightdash/issues/3979

**Closed by TuringLovesDeathMetal** 2023-09-21 10:38 UTC
Labels: 🐛 bug, 📈 chart config
