### ISSUE TITLE
Charts: Data displaying as stacked after removing group

### ISSUE THREAD

**Issue by bhavna-shukla** [lightdash/lightdash#9851] opened 2024-04-22 19:15 UTC
### Description

On editing a stacked dashboard by removing group by column and adding another metric -  Seeing results in charts as stacked, thought group by columns are removed.

### Steps to Reproduce the Bug or Issue

1) Create a test dashboard with stacked chart/s
2) Update /Edit Chart (Stacked)
     a) Remove Col (used in Group)
     b) Add another metric
3) Run Query
4) Update Chart - add both metrics in y axis

Actual Result:
Results in charts are displaying as stacked, even though group by is deleted
Expected Result:
Chart shall not be displayed as stacked on deleting group by .

<img width="1770" alt="image" src="https://github.com/lightdash/lightdash/assets/167811334/48427df4-e50f-4c1c-9f26-2c9d22614fbd">

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment] 2024-04-23 08:51
Closing this issue as a duplicate of: https://github.com/lightdash/lightdash/issues/9851

**Closed by TuringLovesDeathMetal** 2024-04-23 08:51 UTC
Labels: 🐛 bug

**Comment by bhavna-shukla** [comment] 2024-04-23 15:07
> Closing this issue as a duplicate of: #9851

What is duplicate bug #?

**Comment by bhavna-shukla** [comment] 2024-04-23 16:22
Looks like https://github.com/lightdash/lightdash/issues/9851 is the original issue, not able to find duplicate #. Can you please add issue# if.
