### ISSUE TITLE
Enable to dynamically settle min or max values in range rule in table view

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#9922] opened 2024-04-30 03:11 UTC
### Description

It would be great to settle min or max values of a range rule in table view.

### What problem does this solve?

We sometimes settle min or max values of a range rule in the table view. Currently, we have to set fixed values to the min and max values in the table form. However, thresholds can be changed over time or with filter conditions. So, it would be great to enable to automatically, dynamically set the min and max value based on cell values too. If we can automatically settle the values, we don't have to edit a saved chart of a table view with range rule(s).

1. We may still want to set fixed values to either or both of the min and max values of the table view.
2. We may want to automatically set the min or max values based on minimum or maximum values of the cell values respectively.
3. We may want to automatically set calculated values to the min or max values based on the target cell values, say about `0.8 * ${max_value}`.

![image](https://github.com/lightdash/lightdash/assets/1523515/6141a2f3-5e65-4f37-be33-b882f7d99816)

**Comment by TuringLovesDeathMetal** [comment] 2024-12-06 10:36
closing this as a duplicate of https://github.com/lightdash/lightdash/issues/4516

**Closed by TuringLovesDeathMetal** 2024-12-06 10:36 UTC
Labels: ✨ feature-request
