### ISSUE TITLE
Make user email address available in sql_on and sql_where

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6692] opened 2023-08-10 14:15 UTC
### Description

Using `${ lightdash.user.email }` similar to attributes `${ lightdash.attributes.some_attr1 }`

User thread: https://lightdash.slack.com/archives/C053ESBT36V/p1689776286272479

### Docs

Upate documentation on `user attributes` with new user.email functionality

**Comment by hamzahc1** [comment] 2024-04-02 09:08
Closing as a duplicate of #6955

**Closed by hamzahc1** 2024-04-02 09:08 UTC
Labels: 📖 documentation, 💜 Customer Support, ✨ feature-request
