### ISSUE TITLE
Nested filters crop input modals like date pickers

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#9698] opened 2024-04-09 15:31 UTC
### Description

[Screencast from 10-04-24 00:30:43.webm](https://github.com/lightdash/lightdash/assets/1983672/624e9558-5a89-4d0a-b7ab-f06f49850ec9)

**Comment by joaoviana** [comment] 2024-08-06 15:26
Believe this has been fixed because I can't reproduce.

Closing this

https://github.com/user-attachments/assets/c8ae5156-3beb-42ad-92a5-11e64808a86c

**Closed by joaoviana** 2024-08-06 15:26 UTC
Labels: 🐛 bug
