### ISSUE TITLE
Liquid Parameters 

### ISSUE THREAD

**Issue by PruthviRajuCh** [lightdash/lightdash#5468] opened 2023-05-12 09:52 UTC
### Description

Liquid Parameters : SQL query written in dbt will get column conditions from filters and runs the query in data source.

**Comment by owlas** [comment] 2023-05-12 10:09
Hey @PruthviRajuCh do you have an example of the kind of SQL you'd want to write?

**Comment by TuringLovesDeathMetal** [comment] 2024-04-19 09:24
Closing this as a duplicate of #4172

**Closed** 2024-04-19 09:24 UTC
Labels: ✨ feature-request
