### ISSUE TITLE
lock specific charts in a dashboard

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7249] opened 2023-09-28 08:24 UTC
### Description

User suggested a feature to lock individual charts within a dashboard. This aims to prevent unintended edits without restricting overall edit access. While dashboard-scoped charts help reduce errors, a locking feature could provide another layer of control.

note:
- admins should be able to bypass locked access
- this feature can be exclusive to "charts that are created within dashboards"

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 15:43
I'm going to close this issue as not planned. 

We've recently released space permissions. 

If the issue is that you want to have specific charts that are "uneditable" except by certain people, then you should add them to a space and restrict the access to edit except by specific users. This would make them uneditable from a dashboard.

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 15:44
more info in hte docs here: https://docs.lightdash.com/guides/spaces#restricted-access-spaces

**Closed by TuringLovesDeathMetal** 2024-07-29 15:43 UTC
Labels: ✨ feature-request, 💜 customer support
