### ISSUE TITLE
Ability to switch an explore's model

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#8076] opened 2023-11-23 23:33 UTC
### Description
Ability to switch an explore's model to another dbt model

### What problem does this solve?
Sometimes models get renamed or a new model version is created. At the moment, there is no easy way to update Lightdash explores to use the new/renamed model.

**Comment by owlas** [comment] 2023-11-24 14:54
Hey @gordonkjlee this is a great request! How would you ideally express this inside your dbt yaml?

**Comment by ZeRego** [comment] 2023-11-24 14:59
Related to #5264

**Comment by TuringLovesDeathMetal** [comment] 2024-05-30 10:00
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/5264

**Closed by TuringLovesDeathMetal** 2024-05-30 10:00 UTC
Labels: ✨ feature-request
