### ISSUE TITLE
Athena integration

### ISSUE THREAD

**Issue by nicor88** [lightdash/lightdash#4940] opened 2023-03-28 14:30 UTC
### Description
Athena is a query engine from AWS (based on presto/trino). It works with different type of data stored in S3, but with the recent integration  of Iceberg  (that allow full crud operation in the data lake) - it allows to build a serverless lakehouse easily if combined with [dbt-athena](https://github.com/dbt-athena/dbt-athena). 
I know that only "verified adapter are supported", but we can make dbt-athena compatible with [lightdash](https://github.com/lightdash/lightdash) if necessary.

### What problem does this solve?

Using Athena with lightdash

**Comment by jankatins** [comment] 2023-04-12 09:56
#789 seems to be a duplicate of this and has 3 more upvotes. https://github.com/lightdash/lightdash/issues/3554 is also probably a duplicate.

**Comment by nicor88** [comment] 2023-04-12 10:37
@jankatins we can close this one, I can put me message in the https://github.com/lightdash/lightdash/issues/3554

Specifically I think that the only "blocker" to make athena as source happening is the verification process, see my "answer" [here](https://github.com/dbt-labs/dbt-core/discussions/7286#discussioncomment-5583762)

**Closed** 2023-04-12 10:38 UTC
Labels: ✨ feature-request
