### ISSUE TITLE
Sorting functionality is not working in genral way under RESULT BLOCK

### ISSUE THREAD

**Issue by rahul3v** [lightdash/lightdash#135] opened 2021-06-28 09:25 UTC
We can't see sorted rows while playing around with sorting in RESULT BLOCK

![sortNotWorking](https://user-images.githubusercontent.com/24385409/123612977-a98bda00-d820-11eb-8c56-3b463f122fed.gif)

**Comment by owlas** [comment] 2021-06-28 09:29
Thanks @rahul3v !

At the moment, you have to rerun the query to enable sort, which is a terrible UX to be honest so I'm really glad you brought this up.

The problem we have is that the entire results set may not be in memory (consider if a query returns 10,000 rows and you only have a row limit of 500).

I think two things are needed here:

1. If the result set is less than the limit (so we know we have everything in memory) then we should just sort in memory, while simultaneously executing the query on the backend. This means results will instant update but we we also sync with the database at the same time (in case data changed).
2. When we **do** need to wait for the query to rerun, it should be obvious in the UI that the sort is "out of sync" with the table. Or that the results are out of date. We don't have that state right now.

**Comment by rahul3v** [comment] 2021-06-28 09:36
Well @owlas, the query runs as per the limit we set, that would not be the problem, 
**we can implement sorting at client side** to toggle around the sorting patterns, that will be great, **reliable and fast**,

I need to check it, before making any changes about it

**Comment by owlas** [comment] 2021-06-28 10:02
Hey @rahul3v - right we can implement sorting client side but only when the rows returned are less than the limit of the query.

e.g If we use LIMIT 500, and get 499 rows returned from the query, we can sort client side
BUT if we use LIMIT 500 and get 500 rows returned from the query, we cannot sort client side

**Comment by rahul3v** [comment] 2021-06-28 10:12
@owlas, It doesn't mater how many rows we are getting, At client side it's just an `array of resultData` for us , so we can implement that

**Comment by ZeRego** [comment] 2021-06-28 10:24
@rahul3v 
Sorting just the data we have in the frontend could provide misleading/wrong information to the user.

Example:
As a company we have 1000 products.
As a user I want to see what are the products with least orders. 

Steps:
1. I query my products with a total orders metric ( notice there is a 500 results limit by default ) 
2. I click to sort total orders ( asc )

Expected: 
- get the 500 products with the least orders, ordered asc 
What would happen:
- get the current 500 products in memory, ordered asc by total orders

**Comment by rahul3v** [comment] 2021-06-28 10:35
@ZeRego , got your point then,
we can trigger the query to run as per the changes we make automatically instead user to trigger it manually :)

**Comment by owlas** [comment] 2021-07-01 08:26
Closing as duplicate of #62

**Closed by owlas** 2021-07-01 08:26 UTC
Labels: bug
