### ISSUE TITLE
Numbers removed from column name

### ISSUE THREAD

**Issue by gc-p** [lightdash/lightdash#1346] opened 2022-02-11 09:54 UTC
### Describe the bug

I would like to be able to have columns such as "2001_A", "2002_A". At the moment, if I have columns with this naming convention, LightDash displays both of these columns as being "A".

### To Reproduce

Have columns named "2001_A", "2002_A", view the column names in LightDash, which are listed as "A" and "A"

### Expected behavior

LightDash correctly reflects "2001_A", "2002_A"

**Comment by ZeRego** [comment] 2022-02-11 09:59
@all-contributors add @gc-p for bug

**Comment by ZeRego** [comment] 2022-02-11 10:09
@djayatillake I suspect we only need to change this util function: https://github.com/lightdash/lightdash/blob/main/packages/common/src/index.ts#L468
And somehow the tests for it are here:
https://github.com/lightdash/lightdash/blob/main/packages/backend/src/exploreCompiler.test.ts#L76

**Comment by owlas** [comment] 2022-02-11 13:17
@ZeRego I'm to blame for the location of the tests. I decided not to implement jest for the common package just for a regression test. But we could!

**Comment by djayatillake** [comment] 2022-02-18 23:36
I'm planning to work on this

**Comment by djayatillake** [comment] 2022-02-18 23:57
Sometimes the best engineering is no engineering...

@TuringLovesDeathMetal @gc-p I recommend closing this issue

**Comment by TuringLovesDeathMetal** [comment] 2022-02-21 17:54
> I actually think this happens like this for a good reason, most data warehouses won't allow you to alias a column or calculated column in a query with a string starting with numeric characters.

@djayatillake totally! I don't think we should break anything by adding this feature 😅 _**but**_ I think that human-readable fields are really important in data analysis.

Metrics shouldn't be a problem (since we append the table name to your metric name - e.g. `7d_active` becomes `users_7d_active`). And you can't have a numeric value to start a table name. 

For table calculations, what if we just used `table_calculation_1` as the id and in the sql, and then the label that you use in your results table could be whatever you want? (special characters and all!)

**Comment by ZeRego** [comment] 2022-02-21 18:04
@TuringLovesDeathMetal 
For this ticket I would recommend just fixing the friendlyName util function.
Table calculations changes could be done under https://github.com/lightdash/lightdash/issues/1206 and https://github.com/lightdash/lightdash/issues/1205

**Comment by djayatillake** [comment] 2022-02-21 19:02
> @djayatillake I suspect we only need to change this util function: https://github.com/lightdash/lightdash/blob/main/packages/common/src/index.ts#L468
> And somehow the tests for it are here:
> https://github.com/lightdash/lightdash/blob/main/packages/backend/src/exploreCompiler.test.ts#L76

@ZeRego I assume you mean https://github.com/lightdash/lightdash/blob/398bbd28502da87a90cc45fc0a112227ba000599/packages/common/src/index.ts#L586

**Closed** 2022-02-22 13:52 UTC
Labels: bug, good first issue
