### ISSUE TITLE
Add a "% change from previous row" table calculation

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4370] opened 2023-02-02 14:05 UTC
### Description

Also closes: #1849 

Instead of using custom sql, provide an option to make a table calculation "% change from previous row" and selecting a specific column in the data.

We would then convert the table calculation to SQL _at run time_ (so we can flexibly change the definition of the table calculation if needed).

Here's an example query: 

```sql
(
  ${table.column_i_want_to_compare} * 100 / 
  LAG(${table.column_i_want_to_compare}) OVER(
    ORDER BY 
      ${table.column_I_want_to_order_by},  -- this is the first column that the table is ordered by
      ${table.optional_other_column_I_want_to_order_by} -- this is the second column that teh table is ordered by (if it exists)
...etc. -- for more columns that teh table is ordered by
  )
) - 100
```

**Comment by hamzahc1** [comment] 2023-02-03 11:13
@owlas Would you envision this working similar to this implementation: https://cloud.google.com/looker/docs/table-calculations#running-column-total (Note there are two ways to apply them in Looker, one is via the column in the results table, the other is in the pop up modal, not sure which you were thinking of!)

**Comment by TuringLovesDeathMetal** [comment] 2023-02-13 10:18
Nice one!

@owlas would we need to include columns to order by? Or would we just use the ordering in the table? 

i.e. 
```
(
  ${table.column_i_want_to_compare} * 100 / 
  LAG(${table.column_i_want_to_compare}) OVER(
    ORDER BY 
      ${table.column_I_want_to_order_by},  -- is this included?
      ${table.optional_other_column_I_want_to_order_by} -- what if I have multiple columns I've ordered by?
  )
) - 100
```

Also, can we add an option to round the results? (this could be in another version, or could be part of this ticket: https://github.com/lightdash/lightdash/issues/3454)

**Comment by owlas** [comment] 2023-02-16 16:24
@TuringLovesDeathMetal I tested this and it works well with multiple sorts too. 

I think this calculation should actually return the raw difference (current / lag - 1) - because when we apply formatting `percent` it actually multiplies it by 100. It would be confusing to return it pre-multiplied by 100, then adding a percent formatting would make it 100*100.

It makes me think that formatting for table calculations should follow straight after this ticket. 

otherwise I think this is ready to go!

Example generated query:

```sql
WITH metrics AS (
    SELECT
        DATE_TRUNC(`pages`.date, MONTH) AS `pages_date_month`,
        `pages`.source AS `pages_source`,
        COUNT(DISTINCT `pages`.id) AS `pages_page_view_count`
    FROM `lightdash-analytics`.`prod`.`pages` AS `pages`


    GROUP BY 1,2
)
SELECT
    *,
    -100 + `pages_page_view_count` * 100 /
        LAG(`pages_page_view_count`, 1) OVER (ORDER BY `pages_date_month` desc, `pages_source`) AS `m`
FROM metrics

ORDER BY `pages_date_month` DESC, `pages_source`
LIMIT 500;
```

Configuration options:
* Source column
* Name
* (in a new ticket, formatting)

**Comment by owlas** [comment] 2023-02-16 16:30
## implementation

## API

In the API table calculations look like this:

```typescript
export type TableCalculation = {
    index?: number;
    name: string;
    displayName: string;
    sql: string;
};
```

I suggest we make these similar to filters:

```typescript
export type TableCalculation = {
    index?: number;
    name: string;
    displayName: string;
    type: 'sql' | 'pct_change';
    config: Record<string,any>;
};
```

```typescript
# Config for a normal table calculation
type Config: {
  sql: string
}
```

The database before migration:

```
    name                                       text    not null,
    display_name                               text    not null,
    "order"                                    integer not null,
    calculation_raw_sql                        text    not null,
    saved_queries_version_id                   integer not null
```

The database after migration - I think this gives the most flexible interface while keeping foreign keys where needed 

```
    name                                       text    not null,
    type                                       text    not null,
    display_name                               text    not null,
    "order"                                    integer not null,
    config                                      jsonb    not null,
    saved_queries_version_id                   integer not null
```

**Comment by ZeRego** [comment] 2023-02-16 17:20
@owlas moving the `sql` property to `config` would be a breaking change for urls where the explore state is in url params. 
Unsure how the FE will behave with the invalid url state. 

Otherwise, this seems good 👍

**Comment by ZeRego** [comment] 2023-02-16 17:23
@owlas @TuringLovesDeathMetal how feasible is it to create custom SQL functions for these options? so the main query stays readable. eg:
```
perc_change_from_previous_row(dimension_id) as table_calculation_1
```

**Comment by TuringLovesDeathMetal** [comment] 2023-02-17 14:18
> I think this calculation should actually return the raw difference (current / lag - 1)

Yep, sounds good! Then we can add percent formatting to start with for our formatting 👌 (honestly, it's the format I want to apply like 80% of the time anyways)

**Comment by the-watchmaker** [comment] 2023-03-07 08:01
I find string snippets of any query forms using ${placeholders} later generate code complexity. I experienced that with PromQL. I had about over a hundred of them lying about everywhere in the codebase. It really hindered scalability because every new exception and a new feature required new PromQL and separate functions to modify the string 😰 The solution was parsing the PromQL into tree nodes and handling the logic per node instead of modifying a string.

a good example is: 
ORDER BY `pages_date_month` DESC, `pages_source`

I would imagine, if we were to handle it as a string, there might be a specific function that takes in params and then generates a string to be placed in multiple placeholders. 

Meanwhile, SQL can be broken down into tree nodes:

```yaml
ORDER BY:
  - name: page_date_month
     direction: DESC
  - name: page_source
```

which means, you can
1. keep SQL string templates 
2. turn the string templates into tree nodes when the app starts
3. graciously modify it
```javascript
percentChangePreviousRow.["ORDER BY"] = someCustomColumns;
```
4. percentChangePreviousRow.toString();

Right now, there aren't many SQLs. So it's all good, I guess. But this is something to consider...

**Comment by owlas** [comment] 2023-08-08 09:19
That would be very cool @the-watchmaker, the idea of parsing sql into individual operations but I'm worried about the reliability of the parse, and whether we could always get an accurate tree.

**Comment by TuringLovesDeathMetal** [comment] 2024-03-20 13:26
I'm closing this issue as not planned since it feels like a duplicate of: #9349

**Closed by TuringLovesDeathMetal** 2024-03-20 13:26 UTC
Labels: ✨ feature-request
