### ISSUE TITLE
Show timestamp of when data was last updated / dbt last run

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#175] opened 2021-07-05 10:52 UTC
It would be helpful to see when dbt was last run so that you know whether you're looking at the "freshest" data available or not.

**Comment by djayatillake** [comment] 2021-07-26 09:34
would be good to see some other metadata around this too, like number of rows appended and whether this is normal and whether the freshness is normal too

**Comment by TuringLovesDeathMetal** [comment] 2021-10-05 09:23
@hamzahc1 do you mean:
1. "I want to know when the data points I'm looking at were last updated" or
2. "I want to know when the code defining my models + fields in Lightdash was last updated"

**Comment by djayatillake** [comment] 2021-12-06 12:14
I do think this one is really helpful and one of the key UI USPs that Lightdash can have over Looker/Tableau/PowerBI. Any idea when it can be worked on? I know acquiring and parsing the manifest for non dbt cloud customers will be challenging.

**Comment by djayatillake** [comment] 2021-12-09 21:21
It could also show what tests exist for a table in an explore and whether they passed or not in the last run, whether the run failed and whether this specific model failed. If a test has failed or a model in the explore failed this could be put in as a warning.

**Comment by TuringLovesDeathMetal** [comment] 2022-01-25 15:58
Closing this because it's a duplicate of #621

**Closed by TuringLovesDeathMetal** 2022-01-25 15:58 UTC
Labels: feature-request
