### ISSUE TITLE
Custom Metrics filter options kept hidden

### ISSUE THREAD

**Issue by Ankush263** [lightdash/lightdash#7744] opened 2023-10-31 09:49 UTC
### Description

https://github.com/lightdash/lightdash/assets/86042508/8e717c0e-afdb-456b-bee1-6ef1858c65db

**Comment by IrakliJani** [comment] 2023-11-02 07:39
duplicate of https://github.com/lightdash/lightdash/issues/7337

**Closed** 2023-11-02 10:44 UTC
Labels: 🐛 bug
