### ISSUE TITLE
Replacing data sources

### ISSUE THREAD

**Issue by zoehua123** [lightdash/lightdash#7117] opened 2023-09-18 23:18 UTC
### Description

It would be great to have a feature that allows us to replace data sources that share the same fields for a table/chart whilst maintaining the layout and composition.

### What problem does this solve?

When renaming a table (sql file), it requires us to recreate entire dashboards since the tiles reference a table name that no longer exists

**Comment by ZeRego** [comment] 2023-10-19 08:58
Looks duplicate of https://github.com/lightdash/lightdash/issues/5264

**Comment by TuringLovesDeathMetal** [comment] 2024-05-30 10:00
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/5264

**Closed by TuringLovesDeathMetal** 2024-05-30 10:00 UTC
Labels: ✨ feature-request
