### ISSUE TITLE
Add Complex Filter Logic to the Explore UI

### ISSUE THREAD

**Issue by jmcdonald-copy-ai** [lightdash/lightdash#4445] opened 2023-02-10 16:15 UTC
### Description

Currently in the UI the only options for multiple filters are <All> or <Any>. Although complex filters can be expressed through tableau calculations or in the configure layer, this requires a level of technical skill beyond most business users. It would be helpful if there were a <Custom> filter logic option option where users could define arbitrary sets of filter conditions such as: 1 and (2 or 3).  

### What problem does this solve?

This would give business users a better way to slice and dice the data, allowing for more insights for users without SQL knowledge.

**Comment by ZeRego** [comment] 2023-02-17 09:19
Duplicate of https://github.com/lightdash/lightdash/issues/3700

**Closed by ZeRego** 2023-02-17 09:19 UTC
Labels: ✨ feature-request
