### ISSUE TITLE
SQL runner charts should be filterable on dashboards

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#11140] opened 2024-08-14 09:56 UTC
### Description

SQL runner charts should be filterable on dashboards. We've had some discussions about how this could work, but we need to figure out the specifics of the design and what is possible.

**Comment by joaoviana** [comment] 2024-09-23 08:30
Duplicate of https://github.com/lightdash/lightdash/issues/11545 (closing this one because 11545 has a customer thread being tracked)

**Closed by joaoviana** 2024-09-23 08:30 UTC
Labels: ✨ feature-request, ✍️ needs spec
