### ISSUE TITLE
add tabs for fields that are in use" in explorer

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7092] opened 2023-09-18 08:21 UTC
### Description

Add a feature to show "In Use" fields in the explore pane, allowing for easier individual field modification or bulk clearing.

![CleanShot 2023-09-18 at 12 18 16@2x](https://github.com/lightdash/lightdash/assets/962095/f0826cea-214d-45f2-a91d-c63da8a1f56d)

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 15:35
closing this as a duplicate of https://github.com/lightdash/lightdash/issues/1668

**Closed by TuringLovesDeathMetal** 2024-07-29 15:35 UTC
Labels: ✨ feature-request
