### ISSUE TITLE
Create project without being forced to connect a git provider

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2944] opened 2022-08-15 08:03 UTC
### Description

The Lightdash CLI makes it very easy to compile and push a Lightdash project directly from the source code (either a local machine or a production CI/CD job). 

However to connect a new project you have to connect a git connection. This is pretty restrictive during onboarding and makes the docs a bit confusing.

Current workflow:
1. Go to Lightdash UI - click create project
2. Type in git credentials
3. Go to command line and push project
4. Go back to UI and hit refresh
5. Now go back to CLI to create previews / deploy

Proposed workflow
1. Go to Lightdash UI to create project (_bonus:_ this is also possible from the CLI)
2. Go to command line and push project
3. Optionally create preview immediately after

**Comment by ZeRego** [comment] 2022-09-12 14:34
Duplicate of #3077

**Closed by ZeRego** 2022-09-12 14:34 UTC
Labels: ✨ feature-request, 🎮 CLI, 🏄 onboarding
