### ISSUE TITLE
Only allow previews to show up in the dropdown of projects for project developers and admins

### ISSUE THREAD

**Issue by timhiebenthal** [lightdash/lightdash#10701] opened 2024-07-11 15:46 UTC
### Description

Would be helpful to disable the preview environments for users 
Or e.g. make it hidden, but accessible by default? (so that you can see it when the link is shared with you, but you cannot find it yourself in the UI)

### What problem does this solve?

Users accidentally entering the preview environment

**Comment by TuringLovesDeathMetal** [comment] 2024-07-12 13:25
👋 Hey @timhiebenthal 

Thanks for opening this issue! I've just updated the title because I think that we still want developers and admins to be able to see these projects from the dropdown. But let me know if you disagree.

**Comment by TuringLovesDeathMetal** [comment] 2024-10-18 17:58
Just closing this issue since it's a duplicate of another issue here! https://github.com/lightdash/lightdash/issues/8307

**Closed by TuringLovesDeathMetal** 2024-10-18 17:58 UTC
Labels: ✨ feature-request, 💜 customer support
