### ISSUE TITLE
Unable to deploy+preview to lightdash using cli with snowflake + private key auth

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#10455] opened 2024-06-18 20:21 UTC
### Description

User encounters an "Invalid JWT token" error when deploying/previewing to Lightdash with Snowflake authentication, despite successful dbt runs. The issue seems related to token expiration and user authentication methods. A workaround using user/password instead of a private key temporarily resolves the issue.

### Steps to Reproduce the Bug or Issue

needs to be reproduced using snowflake + private key authentication

### Cloud or self-hosting

None

**Comment by jpetey75** [comment] 2024-09-26 11:12
closing as a duplicate of https://github.com/lightdash/lightdash/issues/6424

**Closed by jpetey75** 2024-09-26 11:12 UTC
Labels: 🐛 bug, 🎮 CLI, 💜 customer support
