### ISSUE TITLE
A custom overview page like dbt-docs

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#7215] opened 2023-09-25 23:51 UTC
### Description
dbt-docs enables us to override the top page of dbt-docs with a custom Jinja2 macro with markdown expressions. If we can show a custom overview page of a Lightdash project, that would be helpful to share information across members.

- https://docs.getdbt.com/docs/collaborate/documentation#setting-a-custom-overview
- https://docs.getdbt.com/docs/collaborate/documentation#custom-project-level-overviews

### What problem does this solve?
Showing a custom page would be useful for administrators and adovocit of Lightdash to give a guidance to users of Lightdash in organizations. In our case, we want to give a list of the links to related external resources, and give rules and policies in our Lightdash projects.

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 15:25
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/9596

**Closed by TuringLovesDeathMetal** 2024-07-29 15:25 UTC
Labels: ✨ feature-request
