### ISSUE TITLE
Group by table calculation so I can compare one value against the average for others 

### ISSUE THREAD

**Issue by skemp15** [lightdash/lightdash#9069] opened 2024-02-22 15:38 UTC
### Description

Currently I would like to compare one firms performance against the average for the rest of the firms on the same graph. I can create a table calculation called 'Is_Firm' that is the firm name for the firm and 'Other' otherwise. However, it does not let me select this table calculation in the grouping option for the graph configuration. 

Example table calculation:
![image](https://github.com/lightdash/lightdash/assets/81624279/075cc756-8283-46d2-ad27-7518f69d1411)

Table calculation can be selected for axis but does not appear in group selection:
![image](https://github.com/lightdash/lightdash/assets/81624279/d4b85f90-b205-4b2c-b495-3d94739cb482)

### What problem does this solve?

This would allow me to compare each of my firm performance against the market by simply making is_firm table calculations, rather than having to make them within DBT.

**Comment by menno-vandebron** [comment] 2024-03-26 17:50
+1

**Comment by TuringLovesDeathMetal** [comment] 2024-04-09 11:51
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/2699

**Closed by TuringLovesDeathMetal** 2024-04-09 11:51 UTC
Labels: ✨ feature-request
