### ISSUE TITLE
Create chart within dashboard from explore and move from space

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8711] opened 2024-01-24 08:04 UTC
### Description

> there should be a way to save a chart not only to a space, but also to a dashboard – basically it would be the same as creating a chart within a dashboard

![image](https://github.com/lightdash/lightdash/assets/1983672/9ea5db42-01a7-4bf5-98f7-90c38fee6563)

> and also there should be a way to move a chart from a space to a dashboard. It would be way easier to maintain an uncluttered LD instance. Now i need to delete a chart and recreate it from within a dashboard

Thread: https://lightdash-community.slack.com/archives/C067S48BHRP/p1706028570040049

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 16:39
I'm going to close this as a duplicate of https://github.com/lightdash/lightdash/issues/7169

**Closed by TuringLovesDeathMetal** 2024-07-29 16:39 UTC
Labels: ✨ feature-request
