### ISSUE TITLE
ability to sync to Google Drive with formatting options

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8196] opened 2023-12-04 14:55 UTC
### Description

ability to sync to Google Drive with options to choose between raw and formatted data.
this should be similar to scheduled deliveries formatting options

![CleanShot 2023-12-04 at 18 51 53@2x](https://github.com/lightdash/lightdash/assets/962095/d0f65055-3633-4239-bbea-167fe18ff76b)

![CleanShot 2023-12-04 at 18 42 58@2x](https://github.com/lightdash/lightdash/assets/962095/779f6837-a230-4d1f-93eb-cb8d193c443a)

**Comment by TuringLovesDeathMetal** [comment] 2023-12-04 16:54
Closed as a duplicate of https://github.com/lightdash/lightdash/issues/7971

**Closed by TuringLovesDeathMetal** 2023-12-04 16:54 UTC
Labels: ✨ feature-request
