### ISSUE TITLE
When I try to update any of my project connection settings, I have to re-enter my service account credentials and github personal access token

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1436] opened 2022-02-22 17:35 UTC
### Describe the bug

Right now, if I try to update my project connection settings, all of my settings stay auto-filled with the previous values, but I have to re-enter the GitHub personal access token and service account credentials (even if I'm not changing these!)

### To Reproduce

<img width="395" alt="image" src="https://user-images.githubusercontent.com/31848148/155186787-f12140c4-5886-4260-882d-d5ae383aa070.png">

### Expected behavior

All of the previous values you had for the project settings should be auto-filled if you try to adjust hte settings - including personal access token and service account credentials

**Comment by ZeRego** [comment] 2022-02-22 17:38
Duplicate of https://github.com/lightdash/lightdash/issues/623

**Closed** 2022-02-25 13:30 UTC
Labels: bug
