### ISSUE TITLE
Chart legend labels get cut off or overlap 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#713] opened 2021-10-29 14:43 UTC
When there is not enough room for a longer legend or label on a chart, the text is cut off so you can't see it or it starts overlapping making it hard to read: 

![Screenshot 2021-10-29 at 15 41 05](https://user-images.githubusercontent.com/14341285/139454965-cf7b0597-6bf9-4700-bb63-be982d782ae4.png)

**Comment by TuringLovesDeathMetal** [comment] 2021-11-08 15:25
closed because this is a duplicate of #541

**Closed by TuringLovesDeathMetal** 2021-11-08 15:25 UTC
Labels: bug
