### ISSUE TITLE
Support Grid and Waterfall chart types in Vega

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#9410] opened 2024-03-18 10:38 UTC
As requested by a user.

**Comment by owlas** [comment] 2024-03-18 10:41
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C05B9N87JPR/p1710251122591829?thread_ts=1710251122.591829&cid=C05B9N87JPR

**Comment by thiagocroce** [comment] 2024-04-04 23:28
+1

**Comment by TuringLovesDeathMetal** [comment] 2024-06-27 13:59
closing this as a duplicate of https://github.com/lightdash/lightdash/issues/8876

**Closed by TuringLovesDeathMetal** 2024-06-27 13:59 UTC
Labels: ✨ feature-request
