### ISSUE TITLE
Sub totals for Pivot Tables

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#7992] opened 2023-11-16 13:36 UTC
### Description

I would like to be able to see sub totals in Pivot Tables, like [how Excel does it](https://support.microsoft.com/en-au/office/subtotal-and-total-fields-in-a-pivottable-173f5b30-b546-4293-87d2-aee638f74e7d).

These are different to the column totals that we already support in Pivots. These would apply to the sub-headings as per #7993

**Comment by 12ian34** [comment] 2023-11-16 13:36
@TuringLovesDeathMetal not sure if you'd prefer to add more context here based on our chat earlier.

**Comment by TuringLovesDeathMetal** [comment] 2024-05-06 07:53
I'm closing this issue as resolved (it's a duplicate of #3120 )

**Closed by TuringLovesDeathMetal** 2024-05-06 07:53 UTC
Labels: ✨ feature-request
