### ISSUE TITLE
Allow the same chart to be on the dashboard more than once

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#7237] opened 2023-09-27 08:58 UTC
### Description
At the moment, a chart can only be on a dashboard once. There may be use cases where it might be desirable to have the same chart in various parts of the dashboard.

### What problem does this solve?
An example is when I want to show some aggregate figures next to several drilled down charts.

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 15:24
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/5539

**Closed by TuringLovesDeathMetal** 2024-07-29 15:24 UTC
Labels: ✨ feature-request
