### ISSUE TITLE
selecting a field in explore crashes the whole page

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8425] opened 2023-12-28 11:06 UTC
### Description

internal slack thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1703714588027499
from the customer video - it happens when editing chart within the dashboard

### To Reproduce

can't reproduce

**Comment by ZeRego** [comment] 2024-01-02 12:59
We suspect this error happens when the Dialpad extension finds a value in the results table that resembles a phone number. The extension will then manipulate the HTML so the user can have the option to "call with Dialpad".
This would explain why it only happens to that user. And only sometimes because it depends on the results displayed at that moment.

Similar thread where translate extensions causes that error https://github.com/facebook/react/issues/11538

[Comment](https://github.com/facebook/react/issues/11538#issuecomment-390386520) explaining why the error occurs
> The problem is that Google Translate replaces text nodes with <font> tags containing translations while React keeps references to the text nodes that are no longer in the DOM tree.


[Comment](https://github.com/facebook/react/issues/11538#issuecomment-417504600) from a react maintainer with a workaround
> I don't think we can fix this in React without making legitimate mistakes hard to find, or making performance worse for common cases.
> Finally, there is a workaround you can use that will fix the error. It will make your app a little bit slower, so it is up to you to try it and determine whether the tradeoff is worth it.

[Comment](https://github.com/facebook/react/issues/11538#issuecomment-588987306) from another user 
> The performance problems are probably negligible. The main problem is that it doesn't solve the issue at all, it just swallows the error. The dom will not mutate correctly with that solution.

Looks like the consensus from that thread is to make sure we have `key` for lists and wrap all texts with `span` elements so React tracks that element reference instead of the text reference.

We are in the process of upgrading to React 18, unclear but likely the issue is still present.

**Comment by joaoviana** [comment] 2024-01-04 09:26
> Looks like the consensus from that thread is to make sure we have key for lists and wrap all texts with span elements so React tracks that element reference instead of the text reference.

I would go for this one as well 👍

**Comment by TuringLovesDeathMetal** [comment] 2024-10-30 16:37
Closing this as not planned - it hasn't been raised again by a customer. Will re-open if needed!

**Closed by TuringLovesDeathMetal** 2024-10-30 16:37 UTC
Labels: 🐛 bug, 💜 customer support
