### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8833] opened 2024-02-02 10:41 UTC
### Description

We can specify a set of "mandatory fields" where users of a table have to select. (E.g. 1: When querying Table A, require users to specify XYZ Dim/Metric in 'Filters' section; E.g. 2: When querying Table A, require users to specify XYZ Dim/Metric in 'Results' section) 

Related to [default filters for explores](https://github.com/lightdash/lightdash/issues/1735)

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 16:42
closing this issue as a duplicate of https://github.com/lightdash/lightdash/issues/7521

**Closed by TuringLovesDeathMetal** 2024-07-29 16:42 UTC
Labels: ✨ feature-request
