### ISSUE TITLE
Custom Y-axis labels appear incorrectly on bar charts 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1618] opened 2022-03-30 09:36 UTC
### Describe the bug

When you enter `hello` in the y-axis label field, the string appears twice as  `hellohello` in the chart. This only seems to affect bar charts.

<img width="924" alt="Screenshot 2022-03-30 at 10 12 50" src="https://user-images.githubusercontent.com/12776522/160799657-b071c8bd-69f2-4ab8-b976-16921f32e792.png">

### To Reproduce
1. Go to the chart config panel `Axes` tab
2. Enter a string eg. 'string' for the Y-axis label
3. Look at the y-axis on your chart
4. It appears to be 'stringstring'

### Expected behavior
The label should read 'string'

**Comment by hamzahc1** [comment] 2022-03-30 10:32
This appears to only affect bar charts right now - I couldn't reproduce the error on other chart types. But definitely a bug on bar charts!

**Comment by PriPatel** [comment] 2022-03-30 10:34
@hamzahc1 Oh nice!! You're right, I only tried on bar charts. I'll update the original comment. Thanks!

**Comment by rephus** [comment] 2022-04-01 07:10
I can replicate 
![image](https://user-images.githubusercontent.com/1983672/161213471-2e520403-c4d7-4a3f-b6a6-e7623a5b187f.png)

@nathaliabj could this be fixed by your recent label PR ? if not , I can take a look at this

**Comment by rephus** [comment] 2022-04-01 07:42
No, @nathaliabj I tested with your branch `fix-missing-functionality-chart-configs` and it didn't fix the issue, so I'll take a look

**Comment by rephus** [comment] 2022-04-01 08:03
We don't duplicate the label on our end, but this bar echart creates 2 tags (start/end) . I'm checking if we can remove one of them..

<img width="645" alt="image" src="https://user-images.githubusercontent.com/1983672/161220275-9019c872-2880-4e54-baa6-54c408c39460.png">

**Comment by rephus** [comment] 2022-04-01 08:34
Sorry I couldn't fix this :(

**Comment by owlas** [comment] 2022-04-01 08:49
No prob, it only happens for bar charts right? It must be something with the `flipAxes` configuration, I'll see if I can find it. So odd!

**Closed** 2022-04-01 12:41 UTC
Labels: bug
