### ISSUE TITLE
Metrics are stacked in the SQL runner (even with no group selected)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7229] opened 2023-09-26 13:22 UTC
### Description

Right now, if you have a dimension with two metrics in the SQL runner, the metrics are stacked on top of each other (even though there's no group selected). I

<img width="1123" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/6e3b9890-a69e-47d4-acf4-d97900ca5ea6">

<img width="1118" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/cfb2f77e-ed41-4ac0-8a4c-9cc9ec243209">

<img width="1114" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/5f4ab120-af55-426c-a0f0-07f7e84483c9">

https://analytics.lightdash.cloud/share/QG6cIJI50CwTsCMjpg17c

f you build the same sort of query in the Explore view, you see that metrics aren't stacked:

<img width="1126" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/8fc55ae4-66a6-4f23-bc4b-e864fb5e1cec">

https://analytics.lightdash.cloud/share/aow0k_lNIQdU-0XUunxjZ 

Unless you have a `group` selected in the SQL runner, metrics shouldn't be stacked.

**Comment by ZeRego** [comment] 2023-09-27 15:56
Possible duplicate of https://github.com/lightdash/lightdash/issues/5131

**Comment by TuringLovesDeathMetal** [comment] 2023-10-05 07:41
^ooh, I think you're totally right!

This only happens if you go:

- bar chart
- then area chart (which we stack by default)
- then back to bar chart

**Comment by joaoviana** [comment] 2023-10-05 14:04
covered here: https://github.com/lightdash/lightdash/pull/7353

**Closed** 2023-10-09 08:47 UTC
Labels: 🐛 bug
