### ISSUE TITLE
Row totals are blank for some metrics in pivot tables

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#10054] opened 2024-05-13 12:00 UTC
### Description

When I create the following pivot table in the demo environment
<img width="958" alt="image" src="https://github.com/lightdash/lightdash/assets/7281432/8e3a6577-8917-4729-832f-18dc7867c0dd">

The row total only shows for $ amounts but not for Numeric amounts.
<img width="653" alt="image" src="https://github.com/lightdash/lightdash/assets/7281432/502bacc8-0052-4ce7-a8a7-1b7439be7b78">

I would have expected row totals to show for all metric types regardless of numeric formats.

### Steps to Reproduce the Bug or Issue

<img width="958" alt="image" src="https://github.com/lightdash/lightdash/assets/7281432/8e3a6577-8917-4729-832f-18dc7867c0dd">

### version

v0.1090.6

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment] 2024-05-13 13:39
👋 Hey Gordon

Row totals in pivot tables [are limited to `count` and `sum` type metrics](https://docs.lightdash.com/guides/visualizing-your-results#table:~:text=Also%2C%20in%20pivot%20tables%2C%20totals%20are%20not%20shown%20for%20count%20distinct%2C%20average%2C%20max%2C%20min%2C%20and%20median%20metric%20types.). Is this a count distinct? 

There's an open issue for this here: https://github.com/lightdash/lightdash/issues/9981

I'm going to close this issue as a duplicate of the issue above unless this is actually a count type! (then feel free to re-open the issue)

**Closed as not planned by TuringLovesDeathMetal** 2024-05-13 13:39 UTC
Labels: 🐛 Bug

**Comment by TuringLovesDeathMetal** [comment] 2024-05-13 13:40
If this is coming from the demo environment, then yes, this is a count distinct metric type (in which case, this isn't supported yet in pivot table totals!)

<img width="584" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/96a7a998-9fc6-41f0-9042-7a4b646aa43d">
