### ISSUE TITLE
I would like to be able to type to filter the dashboard list when adding a chart to dashboard

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#6781] opened 2023-08-16 14:41 UTC
### Description

I was expecting to be able to type here. It would make adding a chart to a specific dashboard much easier if I were able to type to filter, just like when searching for metrics/dimensions to select in the Explore view Sidebar.

<img width="440" alt="image" src="https://github.com/lightdash/lightdash/assets/9979944/c985d838-406c-45e4-80b4-cfa7d50b380e">

### What problem does this solve?

Increases ease of adding a chart to dashboard.

**Comment by PriPatel** [comment] 2023-08-17 08:39
This looks like a bug - I'm pretty sure you could type to filter here.

**Comment by ujwalkumar1995** [comment] 2023-08-19 21:13
Hey @PriPatel 
I am able to reproduce this issue from the latest code in my local machine. I may have a fix for this.
Would be happy to raise a PR.
Could you please assign me the issue?

**Comment by PriPatel** [comment] 2023-08-21 08:52
Hi @ujwalkumar1995 - Thanks for your interest - Yes, go for it!
I would recommend using the searchable prop available in Mantine's Select components: https://mantine.dev/core/select/#searchable

**Closed** 2023-08-22 09:08 UTC
Labels: ✨ feature-request
