### ISSUE TITLE
group_label for tables

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#4871] opened 2023-03-21 08:14 UTC
### Description

Add `group_label` feature for tables to enable folders on a table level.

### What problem does this solve?

It can be challenging to choose the correct table. 

Putting tables in folders can make this more manageable.

**Comment by TuringLovesDeathMetal** [comment] 2023-03-21 08:22
👋 hey @Martin-Carlsson I think this one's a duplicate of this issue 👀 

https://github.com/lightdash/lightdash/issues/3353

I'm going to close it in favour of the old one!

I'll also send it in the Ageras slack channel and tag you so you can follow along with updates from Cloudy :)

**Closed by TuringLovesDeathMetal** 2023-03-21 08:22 UTC
Labels: ✨ feature-request
