### ISSUE TITLE
Reference lines are broken on week-based axes

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#10027] opened 2024-05-09 15:19 UTC
### Description

Reference lines are broken on week-based axes

### Steps to Reproduce the Bug or Issue

Create a chart with a WEEK data type on one axis. Try to add a reference line. 

### Cloud or self-hosting

None

**Comment by magnew** [comment] 2024-05-14 10:40
This is caused be the fact that we moved weeks to use a categorical axis. We suspected there would be some tradeoffs and this is the most painful tradeoff we've seen. Reference lines can't be added to any value on a categorical axis, then have to line up with a category. So you can have a reference line that corresponds with week-start, but not Wednesday, for example. A couple of options here:

- Keep the limitation that lines can only be on weeks, but make it more clear
- Use a numeric axis when there is a reference line is added. This will be a little weird with the labels changing. 
- Try using a separate axis for the reference lines and hide everything but the line. This might work, might not. And might be very hard to get right. 
- Go back to the drawing board with trying to customize numeric axes in such a way that we can get the labels we want and keep the lines.

**Comment by joaoviana** [comment] 2024-08-06 15:21
Similar to: https://github.com/lightdash/lightdash/issues/10419

**Comment by TuringLovesDeathMetal** [comment] 2024-11-11 08:10
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/10419

**Closed by TuringLovesDeathMetal** 2024-11-11 08:10 UTC
Labels: 🐛 bug
