### ISSUE TITLE
Add timezone support for scheduled deliveries

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#9387] opened 2024-03-15 11:20 UTC
### Description

add timezone support for scheduled report deliveries. 

![image](https://github.com/lightdash/lightdash/assets/962095/955ba4ca-54eb-400c-af25-9aee5dd22053)

### What problem does this solve?

This feature will enable users to set and adjust timezones for their report schedules, ensuring consistent delivery times regardless of Daylight Saving Time changes.

It also solves the problem of users having to manually convert times between their current timezone and UTC.

**Comment by owlas** [comment] 2024-03-15 11:21
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710175646725509?thread_ts=1710175646.725509&cid=C03MG2VTR08

**Comment by ayush117** [comment] 2024-04-13 11:36
Hi @IrakliJani, I've addressed the concerns in issue #9738 . Could you please take a moment to review my work and provide feedback? Thank you!

**Comment by IrakliJani** [comment] 2024-04-15 07:06
Appreciate it @ayush117 🙌  we'll have a look to the PR shortly

**Comment by jpetey75** [comment] 2024-06-17 21:13
This issue is a duplicate of https://github.com/lightdash/lightdash/issues/4958 so I will close it in favor of that one.

**Closed by jpetey75** 2024-06-17 21:13 UTC
Labels: ✨ feature-request
