### ISSUE TITLE
Interacting with a dashboard filter should feel different when 'I'm viewing it' vs 'when I'm editing it'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6371] opened 2023-07-18 08:32 UTC
### Full configuration

Shows when:
- User is in edit mode (for all filter types)
- User is in view mode and is adding / editing a temporary filter

<img width="444" alt="Screenshot 2023-07-25 at 17 00 00" src="https://github.com/lightdash/lightdash/assets/12776522/5dd71490-fd7d-49bc-9da4-78500aa45624">
<img width="304" alt="Screenshot 2023-07-25 at 17 01 44" src="https://github.com/lightdash/lightdash/assets/12776522/b419eab3-76a0-4cb7-a7eb-b0a329036a19">

You should be able to:
- [ ] Update the dimension
- [ ] Update the default operator
- [ ] Update the default value
- [ ] Rename filter label
- [ ] Update the tile configuration

### Simpler UI

Shows when:
- User is in view mode and editing a permanent filter

<img width="326" alt="Screenshot 2023-07-25 at 16 59 50" src="https://github.com/lightdash/lightdash/assets/12776522/d08d13c4-edfe-419d-bf19-980b317b1952">

You should be able to:
- [ ]  Update the default operator
- [ ]  Update the default value

**Comment by owlas** [comment] 2023-07-26 09:04
Dupe of #6478

**Closed by owlas** 2023-07-26 09:04 UTC
Labels: 🖥 frontend
