### ISSUE TITLE
Project Editor with Group Edit access cannot edit anything.

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#10454] opened 2024-06-18 20:10 UTC
### Description

permissions set from admin:

![CleanShot 2024-06-19 at 00 08 20@2x](https://github.com/lightdash/lightdash/assets/962095/5f4356b3-f966-4414-9ae9-da66635d77f2)
![CleanShot 2024-06-19 at 00 08 01@2x](https://github.com/lightdash/lightdash/assets/962095/a6461747-27e1-4e55-a9d5-389e38c288d1)

permissions from user side:

![CleanShot 2024-06-19 at 00 09 12@2x](https://github.com/lightdash/lightdash/assets/962095/5d1ba0bb-8948-455a-9f4f-7645f581bc3d)
![CleanShot 2024-06-19 at 00 09 18@2x](https://github.com/lightdash/lightdash/assets/962095/cc61126d-4aa0-4ab9-a1dc-07595830c84e)
![CleanShot 2024-06-19 at 00 09 29@2x](https://github.com/lightdash/lightdash/assets/962095/2213a6e4-ceb7-43cf-8659-a01ef4a2c84f)

### Steps to Reproduce the Bug or Issue

1. invite user
2. give edit access to the project
3. give edit access to the space
4. login as invited user
5. try to edit anything inside the space.
6. 💥 

### Cloud or self-hosting

None

**Comment by IrakliJani** [comment] 2024-06-18 20:11
thread: https://github.com/lightdash/lightdash/issues/10454

**Comment by IrakliJani** [comment] 2024-06-18 20:15
this is most likely related to this ticket https://github.com/lightdash/lightdash/issues/10165 where we display one thing and interpret another

**Comment by joaoviana** [comment] 2024-07-01 10:56
and related to #10553

**Comment by almeidabbm** [comment] 2024-07-03 08:55
I haven't been able to reproduce this, here's the internal thread link for some context: https://lightdash.slack.com/archives/C02GQKJK84Q/p1719846607997479

**Comment by TuringLovesDeathMetal** [comment] 2024-07-30 09:37
Closing this issue as not planned as we were not able to reproduce

**Closed by TuringLovesDeathMetal** 2024-07-30 09:37 UTC
Labels: 🐛 bug
