### ISSUE TITLE
Add Description Field to Lightdash Spaces

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#8248] opened 2023-12-08 13:05 UTC
### Description

Add the ability to include a description for each Space in Lightdash, allowing users to provide more context and details about the Space's purpose and contents.

### What problem does this solve?

This feature would enhance the usability of Spaces by allowing users to share more information about the Space than what can be conveyed in the Space title alone. It would be particularly helpful for new team members to understand the context of the Space, and for all users to quickly grasp the focus and contents of different Spaces.

**Comment by jpetey75** [comment] 2024-08-13 01:00
closing as a duplicate of https://github.com/lightdash/lightdash/issues/3892

**Closed by jpetey75** 2024-08-13 01:00 UTC
Labels: ✨ feature-request
