### ISSUE TITLE
add "load more" or "infinite scrolling" to filter autocomplete

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7576] opened 2023-10-23 05:34 UTC
### Description

add "load more" or "infinite scrolling" to filter autocomplete

### What problem does this solve?

This solves the issue of limited search results by allowing users to expand the list incrementally. It will make it easier for users to find and select items in long lists without having to search manually for each one.

implement this after https://github.com/lightdash/lightdash/issues/6730

![CleanShot 2023-10-23 at 09 33 41@2x](https://github.com/lightdash/lightdash/assets/962095/e3f61786-982e-4669-9fab-57b1e1cc3624)

**Comment by iMac7** [comment] 2023-11-12 08:29
I'd like to attempt this but I'm not sure of the scope. Would the API need to be paginated for this, or is it paginated already?

**Comment by TuringLovesDeathMetal** [comment] 2024-07-29 14:23
Closing this as a duplicate of #3290

**Closed by TuringLovesDeathMetal** 2024-07-29 14:23 UTC
Labels: ✨ feature-request, 💜 customer support
