### ISSUE TITLE
Strange side effects when deleting dashboard filter

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#6784] opened 2023-08-16 15:41 UTC
### Description
When addinga dashboard filter, all graphs are filtered as expected. When I delete that same filter, it seems some of the chart-level configuration is ignored. See images below:

A chart within my dashboard **before** applying filter:
![Screenshot from 2023-08-16 10-26-44](https://github.com/lightdash/lightdash/assets/116363294/1d9b81a7-0380-4778-a32b-5fc4f51421c3)

The chart **after** applying filter:
![Screenshot from 2023-08-16 10-27-54](https://github.com/lightdash/lightdash/assets/116363294/6603eb52-6db0-4243-aad8-874fb80d0359)

The chart after deleting filter:
![Screenshot from 2023-08-16 10-28-33](https://github.com/lightdash/lightdash/assets/116363294/48370230-9ac5-49cc-8a5b-4fbec4296f2d)

### To Reproduce
1. Create a chart.
2. Customize some of the `Config -> Series` settings (hide/rename/change color of some of the series).
3. Add chart to a dashboard
4. Apply a new dashboard filter
5. Delete filter

### App Version
lightdash: 0.744.1
dbt-postgres: 1.5

**Comment by serene-capybara** [comment] 2023-08-16 15:47
I was able to reproduce this particular example several times, but I'll add that I have also seen all line charts in my dashboard become bar charts, ostensibly due to creating/deleting a dashboard filter.

**Comment by magnew** [comment] 2023-09-27 15:18
@serene-capybara Thanks for the report! Strange indeed. I'm looking into this and I can't get it to happen. Have you seen it recently? We have changed some of the way dashboards get serialized, so maybe it's no longer there. 

If you do see it maybe you can tell me a little more. Any chance you have some kind of filter that shows this somewhat consistently?

**Comment by TuringLovesDeathMetal** [comment] 2023-10-02 14:23
Closing this issue as we're not able to reproduce it - will reopen if we run into this again!

**Closed by TuringLovesDeathMetal** 2023-10-02 14:23 UTC
Labels: 🐛 bug
