### ISSUE TITLE
long metrics names return null values

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8746] opened 2024-01-26 15:00 UTC
### Description

LD concatenates table name and metric name when generating a query to the database. However, if the concatenated name is long enough, the metric returns NULL values. In my case the table name was 31 chars.

1st screenshot: the metric name is 4 chars, concatenated name 36 chars - no problems

![image](https://github.com/lightdash/lightdash/assets/1983672/f32190c3-9a5b-41a4-9426-c281c786dbfd)

2nd screenshot: the same metric has a name of 34 chars, concatenated name 66 chars - NULL values

![image](https://github.com/lightdash/lightdash/assets/1983672/4ae4701d-b61f-40a4-b0b8-a380b5a67897)

Thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1706184281214839

### App Version

0.960.1

**Comment by ZeRego** [comment] 2024-03-20 16:09
duplicate of https://github.com/lightdash/lightdash/issues/7759

**Closed by ZeRego** 2024-03-20 16:09 UTC
Labels: 🐛 bug, 💜 customer support
