### ISSUE TITLE
Fail to fetch data w/ spark adapter

### ISSUE THREAD

**Issue by skame** [lightdash/lightdash#177] opened 2021-07-05 13:47 UTC
I tried to use spark adapter with following docker image.

```
FROM lightdash/lightdash:0.2.7

RUN apt-get update ; apt-get install -y --no-install-recommends libsasl2-dev
RUN pip install -U dbt==0.19.2
RUN pip install 'dbt-spark[PyHive]'
```

When I run query, results field is empty. And Export CSV output is also empty 500 lines.

![image](https://user-images.githubusercontent.com/1732972/124475303-83e07100-dddc-11eb-809a-a79a1b5610aa.png)

I doubt SQL query include extra-two-'d' as follows (metric: Num_users, Dimension: Org_1st).

```
SELECT
  testmart.org_1st AS dtestmart_org_1std,
  COUNT(testmart.count_user) AS dtestmart_num_usersd
FROM dbt.testmart AS testmart


GROUP BY 1
```

I think it will right.
```
SELECT
  testmart.org_1st AS "testmart_org_1st",
  COUNT(testmart.count_user) AS "testmart_num_users"
FROM dbt.testmart AS testmart


GROUP BY 1
```

 /usr/app/dbt/logs/dbt.log include right numbers.

```
2021-07-05 12:59:19.606216 (Thread-1): TFetchResultsResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), hasMoreRows=False, results=TRowSet(startRowOffset=0, rows=[], columns=[TColumn(boolVal=None, byteVal=None, i16Val=None, i32Val=None, i64Val=None, doubleVal=None, stringVal=TStringColumn(values=[(   snip   ), i64Val=TI64Column(values=[9492, 1704, 13997, 755, 1650, 4686, 912, 2132, 912, 4260, 912, 3830, 4664, 7477, 10262, 912, 4686, 852, 2280, 1638, 4200, 4039, 6384, 2966, 5964, 5599, 3192, 3437, 12218, 5837, 4681, 4260, 10741, 1212, 3072, 3499, 1764, 570], nulls=b'\x00'), doubleVal=None, stringVal=None, binaryVal=None)], binaryColumns=None, columnCount=None))
```

 I also tried dbt-presto and it went fine.

**Comment by owlas** [comment] 2021-07-05 14:00
Hey @skame 

Thanks so much for trying this out with spark and presto, we haven't tested these yet! 

A few questions:

### dockerfile

This is definitely the right approach, are there any additional drivers needed by `dbt-spark` ?  I haven't tried it.

### missing data

It's interesting that you get 500 empty rows. Could I ask you to check the API response you're getting by using your browser's develop tools?

You can see instructions about how to open them here (it's very quick): https://balsamiq.com/support/faqs/browserconsole/

In this example below, I'm using chrome's devtools. Could you do the following:
1. Open the "network" tab
2. Rerun your query
3. Look for an api call to `/runQuery` and look at the results. What's in the `rows` section?

**Comment by skame** [comment] 2021-07-05 14:40
Thank you for your reply.

## dockerfile

[dbt-spark](https://github.com/dbt-labs/dbt-spark) has two modes, dbt-spark[ODBC] and dbt-spark[PyHive]. I use dbt-spark[PyHive] so I installed dbt-spark[PyHive]. And it require sasl-dev on compile, so I installed libsasl2-dev.

```
# pip list|grep dbt
dbt                        0.19.2
dbt-bigquery               0.19.2
dbt-core                   0.19.2
dbt-postgres               0.19.2
dbt-redshift               0.19.2
dbt-snowflake              0.19.2
dbt-spark                  0.19.2
```

## missing data

/runQuery looks like include right data, but main table include no data on chrome.

![image](https://user-images.githubusercontent.com/1732972/124487610-e429df80-dde9-11eb-97d3-ee6e120cdef5.png)

**Comment by owlas** [comment] 2021-07-05 14:49
Awesome!! So the backend seems to be working. That's epic @skame ! I'm going to add you as a contributor for both bug reporting and design because this is so cool.

But the bad news is that the frontend isn't rendering that data.

A quick question, do you know what sql dialect you're using with spark? e.g are you using standard ansi sql with spark sql 3.0: https://spark.apache.org/docs/latest/sql-ref-ansi-compliance.html 

I can't guarantee that the queries will be constructed successfully (we've been targeting bigquery/snowflake/postgres initially). If you see anything in the rendered SQL string (bottom of the UI) that doesn't look right for your target spark cluster, be sure to let us know.

**Comment by owlas** [comment] 2021-07-05 14:49
@all-contributors add @skame for bugs, design

**Comment by skame** [comment] 2021-07-05 15:05
Thanks!

I use spark thrift interface for connecting hadoop hive cluster, so SQL will not be ansi.
And my environment is spark SQL 2.3.

The result of `SELECT 2147483647 + 1;` is `-2147483648`.

**Comment by owlas** [comment] 2021-07-05 15:18
Cool. Then i wouldn't be surprised if you get some queries failing, until we release support officially for spark sql versions

**Comment by skame** [comment] 2021-07-05 21:58
I see, but the query looks basically correct except for quote.

ref. https://github.com/lightdash/lightdash/issues/177#issue-937110449

**Comment by owlas** [comment] 2021-07-06 12:53
@skame do you have any query results that you can share? If possible it would be great to get the exact response you got from the `/runQuery` api so I can reproduce the problem. 

I just noticed there are some unicode characters, for example

**Comment by skame** [comment] 2021-07-06 14:40
I made simple case as follows.

![image](https://user-images.githubusercontent.com/1732972/124619045-44388880-deb3-11eb-9aa8-c385dc17fe7c.png)
![image](https://user-images.githubusercontent.com/1732972/124619152-5c100c80-deb3-11eb-9934-16132095f253.png)

Result of direct spark sql query.
```
SELECT
  lightdash_test.org AS dlightdash_test_orgd,
  COUNT(lightdash_test.count_entryday) AS dlightdash_test_count_entryd
FROM dbt_newnormal.lightdash_test AS lightdash_test


GROUP BY 1

LIMIT 500
```
 
```
+-----------------------+-------------------------------+--+
| dlightdash_test_orgd  | dlightdash_test_count_entryd  |
+-----------------------+-------------------------------+--+
| 1                     | 1                             |
| 3                     | 1                             |
| 2                     | 1                             |
| 0                     | 1                             |
+-----------------------+-------------------------------+--+
```

**Comment by owlas** [comment] 2021-07-06 14:45
That's perfect, thanks @skame - looking into it now

**Comment by owlas** [comment] 2021-07-07 07:37
Hey @skame 

As you said, the query we generate doesn't have the "d" but the column names returned from the query have 'd' prepended and appended to each column name. 

Is that usual for pyhive? I've never used the driver. 

This is the reason it's not rendering. The table is looking for a column called "lightdash_test_org" but can't find it. The column has been renamed "dlightdash_test_org". 

Is that something you've seen before?

**Comment by skame** [comment] 2021-07-07 10:08
I've never seen such a situation.

For example metabase also use pyhive for visualization.

I doubt that 'd's are generated top and bottom, "lightdash_test_org" -> "dlightdash_test_orgd", so some of the quotation/escape string generate 'd'.

**Comment by owlas** [comment] 2021-07-07 10:20
Thanks @skame  - I think I've found the problem. See #201 

I'll let you know when I've released the update

**Comment by owlas** [comment] 2021-07-07 12:27
@skame

**Comment by owlas** [comment] 2021-07-07 13:04
@skame now available if you pull the latest version:

```
docker pull lightdash/lightdash:latest
```

**Comment by owlas** [comment] 2021-07-07 13:04
You can see if you're running the latest in the bottom left of the UI - should say `0.3.2`

<img width="688" alt="Screenshot 2021-07-07 at 14 04 15" src="https://user-images.githubusercontent.com/11660098/124763758-37a44680-df2c-11eb-8863-59c934439f88.png">

**Comment by skame** [comment] 2021-07-07 13:36
Thank you! I got dashboard w/ data!

I had to add following two lines for dbt-spark and I could connect spark2 thrift server.
# type: spark, method: thrift in ~/.dbt/profiles.yml

```
RUN apt-get update && apt-get install -y --no-install-recommends libsasl2-dev
RUN /usr/local/venv/bin/pip install 'dbt-spark[PyHive]'
```

![image](https://user-images.githubusercontent.com/1732972/124768109-5bd74600-df73-11eb-9e8f-6b7ad94d1085.png)

**Comment by owlas** [comment] 2021-07-07 13:59
That's awesome! I'm really pleased we've got this working. Please let us know if you hit any other problems with pyhive / pyspark.

I'm going to close this issue for now.

Would love to hear more about what you're working on. You can always chat with the devs at:

* https://community.lightdash.com
* or https://community.getdbt.com in the #tools-lightdash channel

**Closed by owlas** 2021-07-07 13:59 UTC
Labels: bug
