### ISSUE TITLE
Sort by when viewing Table chart

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#5831] opened 2023-06-09 10:26 UTC
### Description

Users can't sort a table chart by one of the columns when viewing the chart.

Reference: 
<img width="1502" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/85945183-3416-4b8e-b945-6738dc53e595">

I would like to be able to click on a column that I want my chart to be sorted by. 

### What problem does this solve?

Convenient and relevant exploration of current Table charts, specially for users that don't have permissions to edit them.

**Comment by TuringLovesDeathMetal** [comment] 2023-06-09 10:38
Closed because it's a duplicate of https://github.com/lightdash/lightdash/issues/3591

**Closed by TuringLovesDeathMetal** 2023-06-09 10:38 UTC
Labels: ✨ feature-request
