### ISSUE TITLE
Generate dbt exposures with a CLI command

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#5437] opened 2023-05-10 23:37 UTC
### Description
Lightdash provides a sub command to add dimentions to dbt property YAML with a `lightdash generate` command. For instance, dbt-metabase provides a command to generate dbt exposures. We may be able to implement a command like this.

https://github.com/gouline/dbt-metabase#exposure-extraction

### What problem does this solve?
We can visually understand what dbt models are used in outside of dbt as we register dbt exposes in our dbt project. 

https://docs.getdbt.com/docs/build/exposures

**Comment by ZeRego** [comment] 2023-05-26 09:19
Closing this ticket. Duplicate of https://github.com/lightdash/lightdash/issues/4062

**Closed by ZeRego** 2023-05-26 09:19 UTC
Labels: ✨ feature-request

**Comment by yu-iskw** [comment] 2023-05-29 01:54
@ZeRego Thank you for sharing the issue.
