### ISSUE TITLE
I want to be able to refer to a pre-existing table calculation when creating a new table calculation

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#12188] opened 2024-10-31 09:10 UTC
### Description

After creating a table calculation, the user would be able to specify that table calculation as an argument in a new table calculation.

### What problem does this solve?

Sometimes, especially when defining relatively complex table calculations, it is helpful to be able to define sub-components of a calculation separately, then combine them later, rather than having one big wall of SQL. In this kind of scenario, currently I will define two or more calculations separately, then copy and paste the SQL into the combined version, which is a bit clunky and can become quite verbose.

**Comment by TuringLovesDeathMetal** [comment] 2024-10-31 09:34
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/404

**Closed by TuringLovesDeathMetal** 2024-10-31 09:34 UTC
Labels: ✨ feature-request
