### ISSUE TITLE
Redshift and postgres forms linked

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1172] opened 2022-01-19 09:23 UTC
### Describe the bug

The values in the postgres and redshift warehouse forms share keys and have linked values. 

If I update the port on one form, it updates on another. This messes with default values, so usually Redshift does not have the default Redshift port but the default postgres port instead.

### To Reproduce

https://www.loom.com/share/8632921f1d244149b7b88580b4d16cb2

### Expected behavior

I expected default values to be set when I start working on a new redshift connection

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

**Comment by ZeRego** [comment] 2022-08-11 10:03
@owlas @rephus seems a duplicate of #761 and has been fixed

**Comment by rephus** [comment] 2022-09-12 06:31
Yes, this doesn't even make sense anymore, we have changed the warehouse form completely. Closing

**Closed by rephus** 2022-09-12 06:31 UTC
Labels: 🐛 bug, 🙋 good first issue
