### ISSUE TITLE
incorrect `MONTH_NAME` ordering in line charts

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8434] opened 2023-12-29 07:22 UTC
### Description

Line charts are displaying months out of order when using `MONTH_NAME` dimensions - months don't follow the correct order.

![image](https://github.com/lightdash/lightdash/assets/962095/8629ab1f-7bf0-499a-9c6e-5e99930b8b21)

**Comment by IrakliJani** [comment] 2023-12-29 07:38
related ticket that does not mention chart-config. keeping both open for now https://github.com/lightdash/lightdash/issues/4095

**Comment by TuringLovesDeathMetal** [comment] 2024-01-16 10:34
^I think this is a duplicate of #4095? I'm going to close this issue in favour of #4095, but we can always reopen/move context if needed!

**Closed by TuringLovesDeathMetal** 2024-01-16 10:34 UTC
Labels: 🐛 bug, 📈 chart config
