### ISSUE TITLE
Copy in alerts should include `%` for decrease and increase

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10980] opened 2024-08-02 11:01 UTC
### Description

Right now, the docs says that `increase by` and `decrease by` are based on % change ([docs](https://docs.lightdash.com/guides/how-to-create-alerts#:~:text=increased/decreased%20by%3A%20Verify%20whether%20the%20percentage%20change%20in%20the%20first%20value%20relative%20to%20the%20second%20value%20exceeds%20the%20specified%20threshold%2C%20either%20by%20increasing%20or%20decreasing.))

But, the copy in the UI makes it look like it's based off of a raw value. 

WE should make it say % in teh UI and also in the alert copy. 

This should say "Pages page view count decreased by **45% or more**":

<img width="790" alt="image" src="https://github.com/user-attachments/assets/e16386d9-59c4-4cdb-bce5-800f06d29c2a">

There should be a % symbol beside the number in the `threshold` box (like in the margins in chart config)
![image](https://github.com/user-attachments/assets/71cdafd8-bb8f-420d-857c-7c56712c33fe)

<img width="610" alt="image" src="https://github.com/user-attachments/assets/2cbc77e4-a0cd-4cb5-8cd3-0f0a6788b5fd">
<img width="368" alt="image" src="https://github.com/user-attachments/assets/e1f8b3ff-0ce5-4c80-afeb-3843610a1f70">

### Steps to Reproduce the Bug or Issue

see above

### Cloud or self-hosting

None

**Comment by PriPatel** [comment] 2024-08-02 11:22
Is this a duplicate of

https://github.com/lightdash/lightdash/issues/8983

**Closed** 2024-08-02 16:57 UTC
Labels: released, ✨ feature-request
