### ISSUE TITLE
Make it possible for dashboard editors to hide the filters from viewers

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6897] opened 2023-08-25 13:36 UTC
### Description

Make it possible for dashboard editors to turn off filter interactions for viewers and hide the filters.

### What problem does this solve?

An editor would be able to create dashboards with a specific filter setup and disable further interaction from viewers. 

From the customer feature request:

"Sometimes you need to set up pretty specific filter to the model to get things as designed for dashboard. And your target audience is not necessary aware of all those attributes to filter. But if filters are just there it's kinda invitation for users to play with them and mess up the designed dashboard logic."

**Comment by TuringLovesDeathMetal** [comment] 2024-08-22 13:15
I'm going to close this issue as a duplicate of https://github.com/lightdash/lightdash/issues/9638

The other issue has more detailed implementation info

**Closed by TuringLovesDeathMetal** 2024-08-22 13:15 UTC
Labels: ✨ feature-request, 👩‍🎨 design, ✍️ needs spec, 💜 customer support
