### ISSUE TITLE
Cohort Analysis - Calculated Dimension

### ISSUE THREAD

**Issue by waaronmorris** [lightdash/lightdash#4094] opened 2023-01-05 18:42 UTC
### Description

As an analyst, I would like to calculate a dimension in the UI. 

### What problem does this solve?

When analyzing cohort analyses (particularly involving development over time), I find it tedious to constantly be editing a yml anytime an end user wants the cohort anchor date to be modified. 

In addition, cohorts are made by 'binning' certain attributes or metrics. Instead of putting this in the yml, this binning should be made dynamic to allow end users to modify the buckets without editing the yml.

**Comment by TuringLovesDeathMetal** [comment] 2023-01-06 09:09
Hey @waaronmorris - thanks for opening this issue :) 

I think we have two similar open issues here: 

#4023 #3233 

I'm going to close this issue as I think it's a duplicate of the other two!

It sounds like you're more interested in the binning with your issue?

**Closed by TuringLovesDeathMetal** 2023-01-06 09:09 UTC
Labels: ✨ feature-request
