### ISSUE TITLE
Table calculation without formula gets stuck on saved charts

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#10411] opened 2024-06-13 18:51 UTC
### Description

Table calculation on saved charts, when created without formula gets stuck and cannot be deleted. 

### Steps to Reproduce the Bug or Issue

1. Go to a saved chart
2. Create a table calculation and name it, save it
3. An error will appear
4. You will not be able to delete that table calculation

Video from user who reported it can be found here: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1718155612894639?thread_ts=1718126519.579879&cid=C03MG2VTR08

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment] 2024-07-18 09:15
Closing tshi as a duplicate of this: https://github.com/lightdash/lightdash/issues/10505

**Closed by TuringLovesDeathMetal** 2024-07-18 09:15 UTC
Labels: 🐛 bug
