### ISSUE TITLE
When a chart is of type table and it is pivoted, export the table viz instead of the results table in the CSV

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7069] opened 2023-09-13 08:25 UTC
### Description

It would be great to have pivot tables in particular in scheduled deliveries of type csv still show up as pivoted. So what we are requesting is that for other viz types when csv exports are scheduled you show results in table, but when the viz type is table, we output the actual table visualization in the csv.

This means we'll have to move some "pivot" logic from the frontend to the backend before generating the CSV.

**Comment by TuringLovesDeathMetal** [comment] 2024-04-16 10:53
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/6838

**Closed by TuringLovesDeathMetal** 2024-04-16 10:53 UTC
Labels: ✨ feature-request
