### ISSUE TITLE
As an admin, I'd like to impersonate one of my users to test permissions and user attributes

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7420] opened 2023-10-11 06:41 UTC
### Description

As an admin, I'd like to impersonate one of my users to test permissions and user attributes

Thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1696973321983039

**Comment by TuringLovesDeathMetal** [comment] 2024-10-22 11:42
closing this as a duplicate of https://github.com/lightdash/lightdash/issues/6083

**Closed by TuringLovesDeathMetal** 2024-10-22 11:42 UTC
Labels: ✨ feature-request
