### ISSUE TITLE
Dashboard exports should include temporary filters if they're applied

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6961] opened 2023-08-31 17:36 UTC
### Description

Slightly different to #6689 and #4425 - This is a situation where a user wants to apply filters or change filter values on the dashboard before exporting it (But not let people actually change the dashboard in edit mode). 

### What problem does this solve?

Users could quickly export customised dashboards without changing the underlying dashboard.

**Comment by hamzahc1** [comment] 2023-08-31 21:43
Link to customer chat: https://lightdash.slack.com/archives/C05F0N3UPSP/p1693501898275189

**Comment by TuringLovesDeathMetal** [comment] 2023-09-01 08:11
@hamzahc1 I think this might be a duplicate of https://github.com/lightdash/lightdash/issues/6906

**Comment by TuringLovesDeathMetal** [comment] 2023-09-01 08:13
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/6906

**Closed by TuringLovesDeathMetal** 2023-09-01 08:13 UTC
Labels: ✨ feature-request
