### ISSUE TITLE
year labels incorrect in chart configuration

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8433] opened 2023-12-29 07:18 UTC
### Description

There's an inconsistency with year labels in chart configurations; a year set to 2023 is displayed as 2022.

This only seems to affect the DATE types and not numeric.

![image](https://github.com/lightdash/lightdash/assets/962095/1b034a95-083f-42be-b125-18da3b9a116a)
![image](https://github.com/lightdash/lightdash/assets/962095/f252ae55-872c-4aff-8e00-c90288ec69bf)

in this image date supposed to be 2022-10
![image](https://github.com/lightdash/lightdash/assets/962095/3ab745a9-eec6-41e1-8b40-6fe5913b0878)

**Comment by rephus** [comment] 2024-01-23 15:38
I feel this is a duplicate of https://github.com/lightdash/lightdash/issues/8505

**Comment by rephus** [comment] 2024-01-23 15:39
Duplicate of https://github.com/lightdash/lightdash/issues/8505

**Closed by rephus** 2024-01-23 15:39 UTC
Labels: 🐛 bug, 📈 chart config
