### ISSUE TITLE
Scheduled deliveries are being sent with charts missing + columns/rows in the wrong place

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6932] opened 2023-08-30 13:00 UTC
There are scheduled deliveries being sent where the format is different to the format applied in teh dashboard, there are charts missing, and values are stacked in different orders. 

Slack thread here: https://lightdash.slack.com/archives/C04FQQU4RL7/p1693385370583959

We should:

1. Fix this bug
2. add more reporting so that we know when this has happened for users (i.e. a delivery hasn't successfully been compiled before being sent) so that we can fix it before they even report it.

**Comment by IrakliJani** [comment] 2023-08-30 13:14
this happens when screen size in width is not enough. it just moves the item to the very bottom

https://github.com/lightdash/lightdash/assets/962095/761a899a-f79a-40d6-89f5-1112da233d39

**Comment by hamzahc1** [comment] 2023-08-30 15:55
@IrakliJani but the scheduled deliver doesn't use the user's window does it? It uses a headless browser?

**Comment by IrakliJani** [comment] 2023-08-30 17:21
@hamzahc1 yeah but headless browser is a browser which just does not open a window - but works the same way. width is hardcoded to 1400 right now

**Comment by TuringLovesDeathMetal** [comment] 2023-09-05 09:43
If we can find the pattern for _**when**_ this is happening, I think that would be a win for now.

**Comment by rephus** [comment] 2023-09-20 11:46
Investigation thread https://lightdash.slack.com/archives/C02GQKJK84Q/p1695204806760969

**Comment by hamzahc1** [comment] 2023-09-30 14:47
Reopening this issue as it’s occurred again. Looking at the PR for this, seems we expected this may happen and planned to look at Grafana to understand more:

https://lightdash.slack.com/archives/C04FQQU4RL7/p1696070669226129?thread_ts=1693385370.583959&channel=C04FQQU4RL7&message_ts=1696070669.226129

**Comment by rephus** [comment] 2023-10-05 07:19
@IrakliJani why is this still in TODO ? it seems your change should fix the issue we got, we just need to release it

**Comment by IrakliJani** [comment] 2023-10-05 10:33
@rephus im not 💯 sure that this is going to solve the issue since I've not been able to reproduce the issue

**Comment by rephus** [comment] 2023-10-05 11:29
well, your fix makes sense, so I guess we can close this or move it to blocked and see if this keeps happening. 

Unless you think we need to take any action at this point.  What do you think @TuringLovesDeathMetal  ?

**Closed** 2023-12-06 10:00 UTC
Labels: 🐛 bug, 💜 customer support
