### ISSUE TITLE
getting error when inviting someone to an org using Okta 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5132] opened 2023-04-18 11:46 UTC
### Description

User can accept invitation to join an org

### To Reproduce

- Send an invite to an org 
- Accept invite
- The frontend is stuck on /join-organization.
- Get this error on the backend: 

> 2023-04-18 08:49:37 [Lightdash] error: Handled error of type ForbiddenError on [PUT] /api/v1/org Cannot register user in a new organization. Ask an existing admin for an invite link.

**Comment by rephus** [comment] 2023-04-18 12:00
Related issue https://github.com/lightdash/lightdash/issues/5114

**Comment by ZeRego** [comment] 2023-04-18 12:02
Duplicate of https://github.com/lightdash/lightdash/issues/5114 
Note that this only happens when using the `/register` page. It won't happen if user uses the invite url.

**Closed** 2023-04-18 13:07 UTC
Labels: 🐛 bug
