### ISSUE TITLE
App doesn't update after deleting a project

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3354] opened 2022-09-30 12:28 UTC
### Description

App should update and redirect the user to the create project page when no more projects are available.

### To Reproduce
![delete project](https://user-images.githubusercontent.com/9117144/193269404-c232c605-b4ed-45e5-b2be-2a7610878ed2.gif)

### App Version

0.268.0

**Comment by TuringLovesDeathMetal** [comment] 2022-09-30 12:42
Duplicate of https://github.com/lightdash/lightdash/issues/3226

**Closed by TuringLovesDeathMetal** 2022-09-30 12:42 UTC
Labels: 🐛 bug, 🖥 frontend
