### ISSUE TITLE
`drill by` should be supported in pie charts

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10043] opened 2024-05-10 15:36 UTC
### Description

Right now, `drill by` is not supported in pie charts. But it should be. 

we should add `drill by` as an option when you click on a metric value in a pie chart.

**Comment by jpetey75** [comment] 2024-06-19 22:32
closing since its a duplicate of https://github.com/lightdash/lightdash/issues/6573

**Closed by jpetey75** 2024-06-19 22:32 UTC
Labels: ✨ feature-request
