### ISSUE TITLE
Expose and document /dashboards endpoint 

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6840] opened 2023-08-22 14:44 UTC
### Description

Move the dashboards endpoint to controllers directory. Annotate it for docs and API generation so it can be discovered and used. 

### What problem does this solve?

Makes dashboard information available to API users.

**Comment by TuringLovesDeathMetal** [comment] 2023-08-30 13:10
Closing as a duplicate of https://github.com/lightdash/lightdash/issues/6887

**Closed by TuringLovesDeathMetal** 2023-08-30 13:10 UTC
Labels: ✨ feature-request

**Comment by ZeRego** [comment] 2023-08-30 14:20
If someone is looking for the answer

```
// all dashboards the user has access to that contain a chart
[GET] api/v1/projects/{projectUuid}/dashboards?chartUuid={chartUuid}
```
