### ISSUE TITLE
In view mode I should be able to clear filter values

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8799] opened 2024-01-31 13:09 UTC
### Description

currently, viewers are not able to empty (clear) boolean filter values unless default is set to "any value". only users who have edit access are able to do that now.

![CleanShot 2024-01-31 at 17 07 38](https://github.com/lightdash/lightdash/assets/962095/c5b06bce-7f9d-47a2-b8f6-baad3ab618dc)

**Comment by IrakliJani** [comment] 2024-02-01 11:35
linked: https://github.com/lightdash/lightdash/issues/7920

**Comment by magnew** [comment] 2024-03-08 11:57
Changed from bug to a feature request as there is some real UI changes to make.

**Comment by magnew** [comment] 2024-03-11 16:39
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/6760

There is a related PR that doesn't fully implement the behavior in this ticket, but may be a helpful reference: https://github.com/lightdash/lightdash/pull/8820

**Closed by magnew** 2024-03-11 16:39 UTC
Labels: ✍️ needs spec, 💜 Customer Support, ✨ feature-request
