### ISSUE TITLE
Description field for Spaces

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#4928] opened 2023-03-28 00:39 UTC
### Description

Description field for Spaces

### What problem does this solve?

We are a lot of people from different departments who work on Lightdash. This means that many Spaces will be created.

It would be great to have the ability to add a few words to a Space.

**Comment by Martin-Carlsson** [comment] 2023-06-06 07:02
Still relevant

**Comment by Martin-Carlsson** [comment] 2023-08-07 06:50
I still think this one is important

**Comment by TuringLovesDeathMetal** [comment] 2024-04-02 07:54
Closing this as a duplicate of #3892

**Closed by TuringLovesDeathMetal** 2024-04-02 07:54 UTC
Labels: ✨ feature-request
